"use strict";

const $ = (id) => document.getElementById(id);
const ui = Object.fromEntries([
  "modePill","progressText","progressFill","saveState","practiceBanner","blockingError","reviewShell","caseEyebrow","caseTitle",
  "overlayToggle","focusToggle","idToggle","evidenceCard","panoramaWrap","panoramaCanvas","assetState","mappingState","fitButton",
  "zoomOutButton","zoomInButton","resetViewButton","fullScreenButton","firstFrameButton","previousFrameButton","playButton",
  "nextFrameButton","centreFrameButton","lastFrameButton","timeline","focusImage","focusAssetState","questionStep","subjectPill",
  "questionKicker","questionTitle","questionHelp","answerArea","backButton","continueButton","welcomeScreen","completionScreen",
  "completionTitle","completionCount","trancheReceipt","lastEvent","globalReceiptRow","globalReceipt","pauseMessage","reviewCompletedButton",
  "nextTrancheButton","confirmDialog","confirmTitle","confirmNext","helpDrawer","helpButton","closeHelp","startRealButton",
  "startPracticeButton","resetPractice"
].map((id) => [id, $(id)]));

const LABELS = {
  VISIBLE_COMPLETE:"Fully visible",VISIBLE_PARTIAL:"Partly visible",FULLY_OCCLUDED_EXPECTED_PRESENT:"Hidden behind someone, but probably still there",
  OUT_OF_FRAME_OR_LEFT_SCENE:"Left the picture",NOT_PRESENT:"Not present",UNCERTAIN:"Not sure",ONE_USEFUL_CANDIDATE:"One useful box",
  MULTIPLE_CANDIDATES:"More than one useful box",MERGED_WITH_OTHER_PEOPLE:"One box covers several people",FRAGMENT_ONLY:"Only a body fragment has a box",
  NO_CANDIDATE:"No useful box",NOT_APPLICABLE:"Not applicable",SAME_PERSON_DUPLICATES:"Same person — duplicate boxes",
  SAME_PERSON_FRAGMENTS:"Same person — body fragments",DIFFERENT_PEOPLE:"Different people",CORRECT_INNER_BAD_OUTER:"Correct smaller person box; larger box is bad",
  MERGED_MULTI_PERSON:"Several people merged into one box",OBJECT_OR_BACKGROUND:"Object or background",SAME_BURST_LOCAL_SUBJECT:"Yes — same person within this clip",
  DIFFERENT_SUBJECT:"No — different person",CANNOT_TELL:"Cannot tell",OUTFIELD_PLAYER:"Outfield player",GOALKEEPER:"Goalkeeper",
  RELEVANT_OFFICIAL:"Relevant official",OTHER_PERSON:"Other person",UNKNOWN_ROLE:"Not sure",ACTIVE_IN_MATCH:"Active in the match",
  WARMING_OR_INACTIVE:"Warming up or inactive",NOT_PLAYER_OR_OFFICIAL:"Not a player or official",UNKNOWN_PARTICIPATION:"Not sure",
  CERTAIN:"Certain",PROBABLE:"Probably",NOT_SURE:"Not sure"
};

const app = {
  mode:"real", allCases:[], cases:[], serverState:null, current:null, frame:4, playing:false, speed:1, timer:null,
  image:null, focusImage:null, assetReady:false, mappingVerified:false, questionKey:"focus_confirmation", history:[],
  data:null, view:{zoom:1,panX:0,panY:0}, pointer:null, inputMode:"pan", readOnly:false
};

function blankData(caseRow) {
  return {burst_id:caseRow.burst_id,current_question:"focus_confirmation",current_frame_sequence:4,playback_speed:1,answers:{},subjects:[],candidate_mappings:[],missed_person_marks:[]};
}
function currentSubject(index){return app.data.subjects[index]}
function ensureSubjects(count){while(app.data.subjects.length<count){let i=app.data.subjects.length;app.data.subjects.push({subject_token:`SUBJECT_${"ABC"[i]}`,anchor_frame_sequence:null,anchor_source_xy:null,visibility:Array(9).fill(null),supply:Array(9).fill(null),occlusion_phases:Array(9).fill("NONE"),occlusion_confirmed:false,continuity:null,role:null,participation:null,certainty:null,relationship:null});}}
function questionParts(key){let m=key.match(/^subject_(\d+)_(.+)$/);return m?{subject:Number(m[1]),kind:m[2]}:{subject:null,kind:key}}
function relevantVisibility(v){return ["VISIBLE_COMPLETE","VISIBLE_PARTIAL","FULLY_OCCLUDED_EXPECTED_PRESENT","UNCERTAIN"].includes(v)}
function needsRelationship(subject){return subject.supply.some((x)=>["MULTIPLE_CANDIDATES","MERGED_WITH_OTHER_PEOPLE","FRAGMENT_ONLY"].includes(x))}
function needsOcclusion(subject){let v=subject.visibility;let reappears=v.some((x,i)=>i>0&&["VISIBLE_COMPLETE","VISIBLE_PARTIAL"].includes(x)&&v.slice(0,i).some((y)=>["FULLY_OCCLUDED_EXPECTED_PRESENT","NOT_PRESENT"].includes(y)));return reappears||v.some((x)=>["VISIBLE_PARTIAL","FULLY_OCCLUDED_EXPECTED_PRESENT"].includes(x))}
function needsContinuity(subject){return needsOcclusion(subject)||needsRelationship(subject)||subject.visibility.includes("UNCERTAIN")}

function questionSequence(){
  let q=["focus_confirmation"];
  for(let i=0;i<app.data.subjects.length;i++){
    let s=app.data.subjects[i];q.push(`subject_${i}_anchor`,`subject_${i}_visibility`,`subject_${i}_supply`);
    if(needsRelationship(s))q.push(`subject_${i}_relationship`);
    if(needsOcclusion(s))q.push(`subject_${i}_occlusion`);
    if(needsContinuity(s))q.push(`subject_${i}_continuity`);
    q.push(`subject_${i}_role`,`subject_${i}_participation`,`subject_${i}_certainty`);
  }
  let focus=app.data.answers.focus_confirmation;
  if(app.data.subjects.length>0&&app.data.subjects.length<3&&(focus==="MULTIPLE_PEOPLE"||app.data.subjects.some((s)=>s.relationship==="DIFFERENT_PEOPLE")))q.push("additional_subject");
  q.push("missed_check");
  if(app.data.answers.missed_check==="YES")q.push("missed_mark");
  q.push("summary");return q;
}

function reviewReady(){return app.assetReady&&app.mappingVerified&&!app.readOnly}
function answerCards(options,selected,onSelect){ui.answerArea.innerHTML="";options.forEach(([value,label,help],index)=>{let b=document.createElement("button");b.type="button";b.className="answer-card"+(selected===value?" selected":"");b.innerHTML=`<span>${label}</span>${help?`<small>${help}</small>`:""}`;b.dataset.value=value;b.onclick=()=>onSelect(value);b.disabled=!reviewReady();b.setAttribute("aria-pressed",selected===value?"true":"false");b.dataset.shortcut=String(index+1);ui.answerArea.appendChild(b)})}
async function chooseAnswer(key,value){if(app.readOnly||!reviewReady())return;app.data.answers[key]=value;if(key==="focus_confirmation"){if(value==="ONE_PERSON"){app.data.subjects=app.data.subjects.slice(0,1);ensureSubjects(1)}else if(value==="MULTIPLE_PEOPLE"){app.data.subjects=app.data.subjects.slice(0,2);ensureSubjects(2)}else app.data.subjects=[]}if(key==="additional_subject"&&value==="ADD"){let next=app.data.subjects.length;ensureSubjects(Math.min(3,next+1));app.history.push(key);app.questionKey=`subject_${next}_anchor`;app.data.current_question=app.questionKey}await saveDraft();renderQuestion()}

function setQuestion(text,help,kicker="ONE PLAIN-ENGLISH STEP"){ui.questionTitle.textContent=text;ui.questionHelp.textContent=help;ui.questionKicker.textContent=kicker}
function renderQuestion(){
  if(!app.current||app.readOnly)return;let seq=questionSequence();if(!seq.includes(app.questionKey))app.questionKey=seq[Math.min(app.history.length,seq.length-1)]||seq[0];
  queueMicrotask(()=>{if(!reviewReady()){ui.answerArea.querySelectorAll("button,input").forEach((control)=>control.disabled=true);ui.continueButton.disabled=true}});
  let pos=seq.indexOf(app.questionKey);ui.questionStep.textContent=`Question ${pos+1} of ${seq.length}`;let p=questionParts(app.questionKey);ui.subjectPill.textContent=p.subject===null?"":`Subject ${"ABC"[p.subject]}`;
  ui.backButton.disabled=pos===0;ui.continueButton.textContent=app.questionKey==="summary"?"Save burst":"Continue";ui.continueButton.disabled=true;app.inputMode="pan";
  if(p.kind==="focus_confirmation"){
    setQuestion("Is there a relevant match person to follow in the highlighted area?","Play or step through the clip first. A player, goalkeeper, or match official counts.","START WITH THE FOCUS AREA");
    answerCards([["ONE_PERSON","Yes — one person"],["MULTIPLE_PEOPLE","Yes — more than one person"],["NO_RELEVANT_PERSON","No relevant person"],["NOT_SURE","Not sure"]],app.data.answers.focus_confirmation,(v)=>chooseAnswer("focus_confirmation",v));
    ui.continueButton.disabled=!app.data.answers.focus_confirmation;return;
  }
  if(p.kind==="anchor"){let s=currentSubject(p.subject);setQuestion(`Click Subject ${"ABC"[p.subject]} in the clearest frame`,"Choose any frame, then click the person in the large panorama. The point stays in source-image coordinates.","CHOOSE A BURST-LOCAL ANCHOR");ui.answerArea.innerHTML=`<div class="anchor-instruction"><b>${s.anchor_source_xy?"Anchor recorded":"Waiting for your click"}</b><br>${s.anchor_source_xy?`Frame ${s.anchor_frame_sequence+1} · source (${s.anchor_source_xy.map(Math.round).join(", ")})`:"Step through the timeline and click the subject."}</div>`;app.inputMode="anchor";ui.continueButton.disabled=!s.anchor_source_xy;return}
  if(p.kind==="visibility"){let s=currentSubject(p.subject);setQuestion("How visible is this person in each frame?","Choose a visibility state, then select frames. Every frame must have an answer.","NINE-FRAME VISIBILITY");renderTimelineEditor(s,"visibility",[["VISIBLE_COMPLETE","Fully visible"],["VISIBLE_PARTIAL","Partly visible"],["FULLY_OCCLUDED_EXPECTED_PRESENT","Hidden, probably still there"],["OUT_OF_FRAME_OR_LEFT_SCENE","Left the picture"],["NOT_PRESENT","Not present"],["UNCERTAIN","Not sure"]]);ui.continueButton.disabled=s.visibility.some((x)=>!x);return}
  if(p.kind==="supply"){let s=currentSubject(p.subject);setQuestion("What useful box evidence exists for this person?","Only applicable frames are shown. On the centre frame, click any relevant visible box; IDs stay hidden unless you switch them on.","CANDIDATE SUPPLY ACROSS TIME");s.visibility.forEach((v,i)=>{if(!relevantVisibility(v))s.supply[i]="NOT_APPLICABLE"});app.inputMode="candidate";renderTimelineEditor(s,"supply",[["ONE_USEFUL_CANDIDATE","One useful box"],["MULTIPLE_CANDIDATES","More than one useful box"],["MERGED_WITH_OTHER_PEOPLE","One box covers several people"],["FRAGMENT_ONLY","Only a body fragment has a box"],["NO_CANDIDATE","No useful box"],["UNCERTAIN","Not sure"]],(i)=>relevantVisibility(s.visibility[i]));ui.continueButton.disabled=s.supply.some((x,i)=>relevantVisibility(s.visibility[i])&&!x);return}
  if(p.kind==="relationship"){let s=currentSubject(p.subject);setQuestion("How are the boxes related?","This appears only because at least one frame has multiple, merged, or fragment evidence.","CONDITIONAL BOX RELATIONSHIP");answerCards([["SAME_PERSON_DUPLICATES",LABELS.SAME_PERSON_DUPLICATES],["SAME_PERSON_FRAGMENTS",LABELS.SAME_PERSON_FRAGMENTS],["DIFFERENT_PEOPLE",LABELS.DIFFERENT_PEOPLE],["CORRECT_INNER_BAD_OUTER",LABELS.CORRECT_INNER_BAD_OUTER],["MERGED_MULTI_PERSON",LABELS.MERGED_MULTI_PERSON],["OBJECT_OR_BACKGROUND",LABELS.OBJECT_OR_BACKGROUND],["UNCERTAIN","Not sure"]],s.relationship,async(v)=>{s.relationship=v;await saveDraft();renderQuestion()});ui.continueButton.disabled=!s.relationship;return}
  if(p.kind==="occlusion"){let s=currentSubject(p.subject);setQuestion("Does this overlap sequence look right?","The suggested phases are only a helper. Nothing is kept as truth until you confirm or correct it.","CONFIRM THE OCCLUSION SEQUENCE");if(!s.occlusion_confirmed)s.occlusion_phases=derivePhases(s.visibility);ui.answerArea.innerHTML=`<div class="timeline-answer-grid">${s.occlusion_phases.map((v,i)=>`<button class="timeline-answer complete" type="button" data-phase-index="${i}">Frame ${i+1}<br><small>${phaseLabel(v)}</small></button>`).join("")}</div><div class="micro-actions"><button id="confirmPhases" type="button">Confirm this sequence</button><button id="uncertainPhases" type="button">Mark sequence as not sure</button></div>`;$("confirmPhases").onclick=async()=>{s.occlusion_confirmed=true;await saveDraft();renderQuestion()};$("uncertainPhases").onclick=async()=>{s.occlusion_phases=Array(9).fill("UNCERTAIN");s.occlusion_confirmed=true;await saveDraft();renderQuestion()};ui.continueButton.disabled=!s.occlusion_confirmed;return}
  if(p.kind==="continuity"){let s=currentSubject(p.subject);setQuestion("Does this look like the same person across the clip?","This answer applies only inside these nine frames.","BURST-LOCAL CONTINUITY ONLY");answerCards([["SAME_BURST_LOCAL_SUBJECT",LABELS.SAME_BURST_LOCAL_SUBJECT],["DIFFERENT_SUBJECT",LABELS.DIFFERENT_SUBJECT],["CANNOT_TELL",LABELS.CANNOT_TELL],["NOT_APPLICABLE",LABELS.NOT_APPLICABLE]],s.continuity,async(v)=>{s.continuity=v;await saveDraft();renderQuestion()});ui.continueButton.disabled=!s.continuity;return}
  if(["role","participation","certainty"].includes(p.kind)){renderSubjectSingle(p.subject,p.kind);return}
  if(p.kind==="additional_subject"){setQuestion("Do you need to follow another person in this clip?","Add another only when the evidence requires it. A burst can contain at most Subject A, B, and C.","OPTIONAL EXTRA SUBJECT");answerCards([["CONTINUE","No — continue"],["ADD",`Yes — add Subject ${"ABC"[app.data.subjects.length]}`]],app.data.answers.additional_subject,(v)=>chooseAnswer("additional_subject",v));ui.continueButton.disabled=!app.data.answers.additional_subject;return}
  if(p.kind==="missed_check"){setQuestion("Is there an important person who had no useful box during any part of this clip?","Check the whole loop for a player, goalkeeper, or relevant official.","WHOLE-BURST CHECK");answerCards([["NO","No"],["YES","Yes — let me mark them"],["NOT_SURE","Not sure"]],app.data.answers.missed_check,(v)=>chooseAnswer("missed_check",v));ui.continueButton.disabled=!app.data.answers.missed_check;return}
  if(p.kind==="missed_mark"){setQuestion("Click the centre of each missed person","Choose the clearest frame, then click in the large panorama. You can remove a mistaken mark.","SOURCE-COORDINATE MARKING");app.inputMode="mark";renderMarks();ui.continueButton.disabled=app.data.missed_person_marks.length===0;return}
  if(p.kind==="summary"){setQuestion("Check this burst before saving","The final event becomes immutable only after the server validates it and writes an acknowledgement receipt.","PLAIN-LANGUAGE SUMMARY");ui.answerArea.innerHTML=summaryHtml();ui.continueButton.disabled=false;return}
}

function renderSubjectSingle(index,kind){let s=currentSubject(index),config={role:["What is this person’s role?","Ask once for this subject.",[["OUTFIELD_PLAYER",LABELS.OUTFIELD_PLAYER],["GOALKEEPER",LABELS.GOALKEEPER],["RELEVANT_OFFICIAL",LABELS.RELEVANT_OFFICIAL],["OTHER_PERSON",LABELS.OTHER_PERSON],["UNKNOWN_ROLE",LABELS.UNKNOWN_ROLE]]],participation:["How are they taking part?","Pitch location and participation are separate.",[["ACTIVE_IN_MATCH",LABELS.ACTIVE_IN_MATCH],["WARMING_OR_INACTIVE",LABELS.WARMING_OR_INACTIVE],["NOT_PLAYER_OR_OFFICIAL",LABELS.NOT_PLAYER_OR_OFFICIAL],["UNKNOWN_PARTICIPATION",LABELS.UNKNOWN_PARTICIPATION]]],certainty:["Overall, how sure are you about this subject?","It is always safe to choose Not sure.",[["CERTAIN",LABELS.CERTAIN],["PROBABLE",LABELS.PROBABLE],["NOT_SURE",LABELS.NOT_SURE]]]}[kind];setQuestion(config[0],config[1],`SUBJECT ${"ABC"[index]} · ONE ANSWER`);answerCards(config[2],s[kind],async(v)=>{s[kind]=v;await saveDraft();renderQuestion()});ui.continueButton.disabled=!s[kind]}
function phaseLabel(v){return {NONE:"No overlap",ENTERING_OCCLUSION:"Entering overlap",OCCLUDED:"Hidden",EXITING_OCCLUSION:"Coming back",UNCERTAIN:"Not sure"}[v]}
function derivePhases(v){return v.map((x,i)=>{if(x==="FULLY_OCCLUDED_EXPECTED_PRESENT")return "OCCLUDED";if(x==="VISIBLE_PARTIAL"){let before=v.slice(0,i).some((y)=>y==="FULLY_OCCLUDED_EXPECTED_PRESENT"),after=v.slice(i+1).some((y)=>y==="FULLY_OCCLUDED_EXPECTED_PRESENT");return before&&!after?"EXITING_OCCLUSION":"ENTERING_OCCLUSION"}return "NONE"})}
function renderTimelineEditor(s,field,options,applicable=()=>true){let selected=app.data.answers[`picker_${app.questionKey}`]||options[0][0];ui.answerArea.innerHTML=`<div class="state-picker">${options.map(([v,l],i)=>`<button type="button" data-state="${v}" class="${selected===v?"selected":""}"><span>${i+1}. ${l}</span></button>`).join("")}</div><div class="micro-actions"><button id="applyAll" type="button">Apply to all shown</button><button id="copyPrevious" type="button">Copy previous</button><button id="undoTimeline" type="button">Clear last</button></div><div class="timeline-answer-grid">${Array.from({length:9},(_,i)=>`<button type="button" data-frame-answer="${i}" class="timeline-answer ${s[field][i]?"complete":""}" ${applicable(i)?"":"disabled"}>Frame ${i+1}<br><small>${s[field][i]?LABELS[s[field][i]]:"Choose"}</small></button>`).join("")}</div>`;ui.answerArea.querySelectorAll("[data-state]").forEach((b)=>b.onclick=()=>{app.data.answers[`picker_${app.questionKey}`]=b.dataset.state;renderQuestion()});ui.answerArea.querySelectorAll("[data-frame-answer]").forEach((b)=>b.onclick=async()=>{let i=Number(b.dataset.frameAnswer);s[field][i]=app.data.answers[`picker_${app.questionKey}`]||options[0][0];app.frame=i;await saveDraft();renderAllEvidence();renderQuestion()});$("applyAll").onclick=async()=>{s[field]=s[field].map((v,i)=>applicable(i)?selected:v);await saveDraft();renderQuestion()};$("copyPrevious").onclick=async()=>{for(let i=1;i<9;i++)if(applicable(i)&&!s[field][i]&&s[field][i-1])s[field][i]=s[field][i-1];await saveDraft();renderQuestion()};$("undoTimeline").onclick=async()=>{for(let i=8;i>=0;i--)if(applicable(i)&&s[field][i]){s[field][i]=null;break}await saveDraft();renderQuestion()}}
function renderMarks(){ui.answerArea.innerHTML=`<div class="mark-instruction"><b>${app.data.missed_person_marks.length} missed ${app.data.missed_person_marks.length===1?"person":"people"} marked.</b><br>Click the large view to add another.</div><div class="subject-list">${app.data.missed_person_marks.map((m,i)=>`<button type="button" data-remove-mark="${i}">Remove mark ${i+1} · frame ${m.frame_sequence+1}</button>`).join("")}</div>`;ui.answerArea.querySelectorAll("[data-remove-mark]").forEach((b)=>b.onclick=async()=>{app.data.missed_person_marks.splice(Number(b.dataset.removeMark),1);await saveDraft();drawPanorama();renderQuestion()})}
function summaryHtml(){let subjectRows=app.data.subjects.map((s)=>`<li><b>Subject ${s.subject_token.slice(-1)}</b> · ${LABELS[s.role]||"Not set"} · ${LABELS[s.participation]||"Not set"} · ${LABELS[s.certainty]||"Not set"}</li>`).join("");return `<ul class="summary-list"><li><b>Focus area:</b> ${focusLabel(app.data.answers.focus_confirmation)}</li>${subjectRows||"<li>No focus subject timeline is being saved.</li>"}<li><b>Whole-burst check:</b> ${app.data.answers.missed_check||"Not sure"}</li><li><b>Source-coordinate marks:</b> ${app.data.missed_person_marks.length}</li></ul>`}
function focusLabel(v){return {ONE_PERSON:"One relevant person",MULTIPLE_PEOPLE:"More than one relevant person",NO_RELEVANT_PERSON:"No relevant person",NOT_SURE:"Not sure"}[v]||"Not answered"}

async function continueQuestion(){if(ui.continueButton.disabled||app.readOnly)return;if(app.questionKey==="summary"){await saveFinal();return}let seq=questionSequence(),index=seq.indexOf(app.questionKey);app.history.push(app.questionKey);app.questionKey=seq[index+1]||"summary";app.data.current_question=app.questionKey;await saveDraft();renderQuestion()}
async function backQuestion(){if(!app.history.length||app.readOnly)return;app.questionKey=app.history.pop();app.data.current_question=app.questionKey;await saveDraft();renderQuestion()}
async function api(path,payload){let response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});let body=await response.json();if(!response.ok||body.ok===false)throw new Error(body.error||`HTTP ${response.status}`);return body}
async function saveDraft(){if(app.readOnly)return;ui.saveState.textContent="Saving…";ui.continueButton.disabled=true;let payload={mode:app.mode,burst_id:app.current.burst_id,current_question:app.questionKey,current_frame_sequence:app.frame,playback_speed:app.speed,answers:app.data.answers,subjects:app.data.subjects,candidate_mappings:app.data.candidate_mappings,missed_person_marks:app.data.missed_person_marks};try{await api("/api/draft",payload);ui.saveState.textContent="Progress saved to server"}catch(e){block(`DRAFT_SAVE_ERROR — ${e.message}`);throw e}}
function eventPayload(){return {mode:app.mode,burst_id:app.current.burst_id,focus_answer:app.data.answers.focus_confirmation,subjects:app.data.subjects.map((s)=>({subject_token:s.subject_token,anchor_frame_sequence:s.anchor_frame_sequence,anchor_source_xy:s.anchor_source_xy,frame_observations:app.current.frames.map((f,i)=>({frame_reference_id:f.frame_reference_id,visibility:s.visibility[i],observation_supply:s.supply[i],occlusion_phase:s.occlusion_phases[i]})),candidate_relationship:s.relationship||"NOT_APPLICABLE",continuity:s.continuity||"NOT_APPLICABLE",role:s.role,participation:s.participation,certainty:s.certainty})),candidate_mappings:app.data.candidate_mappings,whole_burst_missed_person_answer:app.data.answers.missed_check,whole_burst_missed_person_marks:app.data.missed_person_marks,source_frame_hashes:app.current.frames.map((f)=>f.source_frame_pixel_sha256),summary_confirmed:true}}
async function saveFinal(){ui.continueButton.disabled=true;ui.continueButton.textContent="Saving safely…";ui.saveState.textContent="Persisting event…";try{let result=await api("/api/save",eventPayload());ui.saveState.textContent=`SAVED — SERVER ACKNOWLEDGED · ${result.event_id}`;if(app.mode==="practice"){await loadMode("practice");return}if(result.tranche_complete){await loadMode("real",app.current.tranche_id);return}await loadMode("real",app.current.tranche_id)}catch(e){block(`FINAL_SAVE_ERROR — ${e.message}`)}}

async function sha256Blob(blob){let bytes=await blob.arrayBuffer(),digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map((x)=>x.toString(16).padStart(2,"0")).join("")}
async function verifiedImage(url,expectedHash){let response=await fetch(url,{cache:"force-cache"});if(!response.ok)throw new Error(`asset HTTP ${response.status}`);let blob=await response.blob();if(await sha256Blob(blob)!==expectedHash)throw new Error("derivative hash mismatch");let objectUrl=URL.createObjectURL(blob),image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error("image decode failed"));image.src=objectUrl});image._objectUrl=objectUrl;return image}
async function loadFrame(index,preservePlayback=false){if(!preservePlayback)stopPlayback();app.frame=Math.max(0,Math.min(8,index));app.data.current_frame_sequence=app.frame;app.assetReady=false;app.mappingVerified=false;ui.mappingState.textContent="CHECKING";renderQuestion();ui.assetState.classList.remove("hidden");ui.focusAssetState.classList.remove("hidden");let frame=app.current.frames[app.frame];try{let [panorama,focus]=await Promise.all([verifiedImage(frame.panorama_url,frame.panorama_sha256),verifiedImage(frame.focus_url,frame.focus_sha256)]);if(app.image?._objectUrl)URL.revokeObjectURL(app.image._objectUrl);if(app.focusImage?._objectUrl)URL.revokeObjectURL(app.focusImage._objectUrl);app.image=panorama;app.focusImage=focus;ui.focusImage.src=focus.src;ui.focusAssetState.classList.add("hidden");app.assetReady=panorama.naturalWidth>0&&panorama.naturalHeight>0&&focus.naturalWidth>0&&focus.naturalHeight>0;app.mappingVerified=app.assetReady&&verifyMapping();ui.mappingState.textContent=app.mappingVerified?"VERIFIED":"FAILED";drawPanorama();pixelContentGate();if(!app.mappingVerified)throw new Error("source/display mapping verification failed");ui.assetState.classList.add("hidden");renderTimeline();renderQuestion();prefetchNext()}catch(e){block(`ASSET_LOAD_ERROR — ${e.message}`)}}
function verifyMapping(){let frame=app.current.frames[app.frame];for(let point of [[0,0],[frame.source_width/2,frame.source_height/2],[frame.source_width,frame.source_height]]){let display=sourceToDisplay(point),round=displayToSource(display);if(Math.hypot(round[0]-point[0],round[1]-point[1])>.5)return false}return true}
function pixelContentGate(){let c=ui.panoramaCanvas,ctx=c.getContext("2d"),w=Math.min(c.width,160),h=Math.min(c.height,96),x=Math.max(0,Math.floor((c.width-w)/2)),y=Math.max(0,Math.floor((c.height-h)/2)),sample=ctx.getImageData(x,y,w,h).data,min=765,max=0,nonBlack=0;for(let i=0;i<sample.length;i+=4){let value=sample[i]+sample[i+1]+sample[i+2];min=Math.min(min,value);max=Math.max(max,value);if(value>48)nonBlack++}if(max-min<24||nonBlack<sample.length/32)throw new Error("blank rendered panorama")}
function canvasMetrics(){let rect=ui.panoramaCanvas.getBoundingClientRect(),frame=app.current.frames[app.frame],scale=Math.min(rect.width/frame.source_width,rect.height/frame.source_height)*app.view.zoom;return {rect,scale,left:(rect.width-frame.source_width*scale)/2+app.view.panX,top:(rect.height-frame.source_height*scale)/2+app.view.panY,dpr:window.devicePixelRatio||1}}
function sourceToDisplay(point){let m=canvasMetrics();return [m.left+point[0]*m.scale,m.top+point[1]*m.scale]}
function displayToSource(point){let m=canvasMetrics();return [(point[0]-m.left)/m.scale,(point[1]-m.top)/m.scale]}
function resizeCanvas(){let rect=ui.panoramaWrap.getBoundingClientRect(),dpr=window.devicePixelRatio||1;ui.panoramaCanvas.width=Math.max(1,Math.round(rect.width*dpr));ui.panoramaCanvas.height=Math.max(1,Math.round(rect.height*dpr));ui.panoramaCanvas.style.width=`${rect.width}px`;ui.panoramaCanvas.style.height=`${rect.height}px`;drawPanorama()}
function drawPanorama(){if(!app.image||!app.current)return;let canvas=ui.panoramaCanvas,ctx=canvas.getContext("2d"),m=canvasMetrics();ctx.setTransform(m.dpr,0,0,m.dpr,0,0);ctx.clearRect(0,0,m.rect.width,m.rect.height);ctx.fillStyle="#080e1d";ctx.fillRect(0,0,m.rect.width,m.rect.height);ctx.drawImage(app.image,m.left,m.top,app.current.frames[app.frame].source_width*m.scale,app.current.frames[app.frame].source_height*m.scale);if(ui.focusToggle.checked){drawBox(ctx,app.current.focus_crop_source_xyxy,"#55a9ff",[10,7],"Focus area")}if(ui.overlayToggle.checked&&app.frame===4){app.current.candidates.forEach((candidate)=>drawBox(ctx,candidate.source_box_xyxy,"#ffd329",[],ui.idToggle.checked?candidate.candidate_id:""))}app.data?.missed_person_marks?.filter((mark)=>mark.frame_sequence===app.frame).forEach((mark,i)=>drawMark(ctx,mark.source_xy,i+1));app.data?.subjects?.filter((s)=>s.anchor_frame_sequence===app.frame&&s.anchor_source_xy).forEach((s)=>drawAnchor(ctx,s.anchor_source_xy,s.subject_token))}
function toggleCandidateAt(source){if(app.frame!==4)return false;let p=questionParts(app.questionKey);if(p.kind!=="supply"||p.subject===null)return false;let hits=app.current.candidates.filter((candidate)=>{let b=candidate.source_box_xyxy;return source[0]>=b[0]&&source[0]<=b[2]&&source[1]>=b[1]&&source[1]<=b[3]});if(!hits.length)return false;let candidate=hits.sort((a,b)=>((a.source_box_xyxy[2]-a.source_box_xyxy[0])*(a.source_box_xyxy[3]-a.source_box_xyxy[1]))-((b.source_box_xyxy[2]-b.source_box_xyxy[0])*(b.source_box_xyxy[3]-b.source_box_xyxy[1])))[0],subject=currentSubject(p.subject),key=`${subject.subject_token}|${app.frame}|${candidate.candidate_id}`,index=app.data.candidate_mappings.findIndex((m)=>m.mapping_key===key);if(index>=0)app.data.candidate_mappings.splice(index,1);else app.data.candidate_mappings.push({mapping_key:key,subject_token:subject.subject_token,frame_sequence:app.frame,frame_reference_id:app.current.frames[app.frame].frame_reference_id,candidate_id:candidate.candidate_id,source_box_xyxy:candidate.source_box_xyxy});saveDraft().then(drawPanorama);return true}
function drawBox(ctx,box,color,dash,label){let a=sourceToDisplay([box[0],box[1]]),b=sourceToDisplay([box[2],box[3]]);ctx.save();ctx.strokeStyle=color;ctx.lineWidth=4;ctx.setLineDash(dash);ctx.strokeRect(a[0],a[1],b[0]-a[0],b[1]-a[1]);if(label){ctx.setLineDash([]);ctx.fillStyle="#111a33dd";ctx.fillRect(a[0],Math.max(0,a[1]-26),Math.max(88,ctx.measureText(label).width+16),25);ctx.fillStyle="#fff";ctx.font="700 13px Segoe UI";ctx.fillText(label,a[0]+7,Math.max(17,a[1]-8))}ctx.restore()}
function drawMark(ctx,point,n){let p=sourceToDisplay(point);ctx.save();ctx.fillStyle="#ff6f6f";ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(p[0],p[1],13,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#fff";ctx.font="bold 13px Arial";ctx.textAlign="center";ctx.fillText(String(n),p[0],p[1]+4);ctx.restore()}
function drawAnchor(ctx,point,token){let p=sourceToDisplay(point);ctx.save();ctx.strokeStyle="#36e0b3";ctx.lineWidth=4;ctx.beginPath();ctx.arc(p[0],p[1],15,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#36e0b3";ctx.font="bold 12px Arial";ctx.fillText(token.replace("SUBJECT_","Subject "),p[0]+20,p[1]+4);ctx.restore()}
function renderTimeline(){ui.timeline.innerHTML="";app.current.frames.forEach((frame,i)=>{let b=document.createElement("button");b.type="button";b.className=`frame-thumb ${i===app.frame?"current":""} ${i===4?"centre":""}`;b.setAttribute("aria-label",`Show frame ${i+1}`);b.innerHTML=`<img src="${frame.panorama_url}" alt="Frame ${i+1}" loading="${Math.abs(i-app.frame)>2?"lazy":"eager"}"><span>${frame.relative_offset_seconds>0?"+":""}${frame.relative_offset_seconds.toFixed(1)}s</span>`;b.onclick=()=>loadFrame(i);ui.timeline.appendChild(b)})}
function renderAllEvidence(){renderTimeline();drawPanorama()}
function stopPlayback(){if(app.timer)clearTimeout(app.timer);app.timer=null;app.playing=false;ui.playButton.textContent="Play"}
function schedulePlayback(){if(!app.playing)return;app.timer=setTimeout(async()=>{await loadFrame((app.frame+1)%9,true);schedulePlayback()},200/app.speed)}
function togglePlayback(){if(app.playing){stopPlayback();return}app.playing=true;ui.playButton.textContent="Pause";schedulePlayback()}
function prefetchNext(){if(app.mode!=="real")return;let i=app.cases.findIndex((c)=>c.burst_id===app.current.burst_id),next=app.cases[i+1];if(!next)return;for(let frame of [next.frames[4]]){let link=document.createElement("link");link.rel="prefetch";link.href=frame.panorama_url;document.head.appendChild(link)}}

async function loadCase(caseRow,draft=null){app.current=caseRow;app.frame=draft?.current_frame_sequence??4;app.speed=draft?.playback_speed??1;app.data=draft?structuredClone(draft):blankData(caseRow);app.questionKey=draft?.current_question||"focus_confirmation";app.history=[];app.view={zoom:1,panX:0,panY:0};app.readOnly=false;ui.caseEyebrow.textContent=`MATCH ${caseRow.match_id} · ${caseRow.half.replace("_"," ")} · ${caseRow.frames[4].resolved_timestamp_seconds.toFixed(2)} SECONDS`;ui.caseTitle.textContent=`Burst ${caseRow.tranche_position||caseRow.practice_position} · nine-frame review`;ui.reviewShell.classList.remove("hidden");ui.welcomeScreen.classList.add("hidden");ui.completionScreen.classList.add("hidden");updateProgress();renderQuestion();renderTimeline();resizeCanvas();await loadFrame(app.frame)}
async function loadMode(mode,tranche=null){app.mode=mode;stopPlayback();ui.saveState.textContent="Loading server state…";let url=`/api/bootstrap?mode=${mode}${tranche?`&tranche=${tranche}`:""}`,response=await fetch(url),payload=await response.json();if(!response.ok)throw new Error(payload.error||"bootstrap failed");app.allCases=payload.cases;app.serverState=payload.state;ui.practiceBanner.classList.toggle("hidden",mode!=="practice");ui.modePill.textContent=mode==="practice"?"Practice · isolated":`${payload.state.tranche_id?.replace("_"," ")} of 6`;if(mode==="real"&&payload.state.tranche_complete){renderCompletion(payload.state);return}if(mode==="practice"&&payload.state.all_practice_complete){renderPracticeComplete();return}app.cases=mode==="practice"?payload.cases:payload.cases.filter((c)=>c.tranche_id===payload.state.tranche_id);let id=payload.state.first_incomplete_burst_id||app.cases[0].burst_id,caseRow=app.cases.find((c)=>c.burst_id===id);await loadCase(caseRow,payload.state.draft);ui.saveState.textContent=payload.state.draft?"Draft restored from server":"Ready · server-backed"}
function updateProgress(){let s=app.serverState,done=s?.completed_count||0,total=s?.total_count||(app.mode==="practice"?3:20);ui.progressText.textContent=`${done} of ${total}`;ui.progressFill.style.width=`${100*done/total}%`}
function renderCompletion(state){ui.reviewShell.classList.add("hidden");ui.welcomeScreen.classList.add("hidden");ui.completionScreen.classList.remove("hidden");let n=Number(state.tranche_id.split("_")[1]);ui.modePill.textContent=`Tranche ${n} complete`;ui.progressText.textContent="20 of 20";ui.progressFill.style.width="100%";ui.completionTitle.textContent=`TRANCHE ${n} COMPLETE`;ui.completionCount.textContent="20 of 20 bursts complete";ui.trancheReceipt.textContent=state.tranche_completion_receipt_id;ui.lastEvent.textContent=state.last_event_id;ui.globalReceiptRow.classList.toggle("hidden",!state.all_cases_complete);ui.globalReceipt.textContent=state.global_completion_receipt_id||"—";ui.nextTrancheButton.classList.toggle("hidden",n===6);ui.nextTrancheButton.textContent=`Start Tranche ${n+1}`;ui.pauseMessage.innerHTML=n===1?"<b>PAUSE HERE — YOU MAY STOP SAFELY</b><span>Pause here and send the completion receipt for validation.<br>You can begin Tranche 2 later without losing progress.</span>":"<b>PAUSE HERE — YOU MAY STOP SAFELY</b><span>This tranche is immutable and read-only. Begin the next tranche only when you are ready.</span>";if(state.all_cases_complete){ui.completionTitle.textContent="ALL TEMPORAL REVIEW COMPLETE";ui.completionCount.textContent="120 of 120 complete";ui.nextTrancheButton.classList.add("hidden")}ui.saveState.textContent="Completion restored from server"}
function renderPracticeComplete(){ui.reviewShell.classList.add("hidden");ui.welcomeScreen.classList.remove("hidden");ui.completionScreen.classList.add("hidden");ui.startPracticeButton.textContent="Practice complete — reset or try again";ui.saveState.textContent="Practice saved outside human truth"}
function block(message){stopPlayback();ui.blockingError.textContent=message;ui.blockingError.classList.remove("hidden");ui.continueButton.disabled=true;ui.saveState.textContent="Stopped safely"}

ui.continueButton.onclick=continueQuestion;ui.backButton.onclick=backQuestion;ui.playButton.onclick=togglePlayback;ui.firstFrameButton.onclick=()=>loadFrame(0);ui.previousFrameButton.onclick=()=>loadFrame(app.frame-1);ui.nextFrameButton.onclick=()=>loadFrame(app.frame+1);ui.centreFrameButton.onclick=()=>loadFrame(4);ui.lastFrameButton.onclick=()=>loadFrame(8);ui.fitButton.onclick=()=>{app.view={zoom:1,panX:0,panY:0};drawPanorama()};ui.resetViewButton.onclick=ui.fitButton.onclick;ui.zoomInButton.onclick=()=>{app.view.zoom=Math.min(5,app.view.zoom*1.25);drawPanorama()};ui.zoomOutButton.onclick=()=>{app.view.zoom=Math.max(1,app.view.zoom/1.25);drawPanorama()};ui.fullScreenButton.onclick=()=>ui.evidenceCard.requestFullscreen();[ui.overlayToggle,ui.focusToggle,ui.idToggle].forEach((x)=>x.onchange=drawPanorama);document.querySelectorAll("[data-speed]").forEach((b)=>b.onclick=()=>{app.speed=Number(b.dataset.speed);document.querySelectorAll("[data-speed]").forEach((x)=>x.classList.toggle("active",x===b));if(app.playing){stopPlayback();togglePlayback()}saveDraft()});
ui.panoramaCanvas.addEventListener("pointerdown",(event)=>{let rect=ui.panoramaCanvas.getBoundingClientRect(),display=[event.clientX-rect.left,event.clientY-rect.top],source=displayToSource(display),frame=app.current.frames[app.frame];if(source[0]<0||source[1]<0||source[0]>frame.source_width||source[1]>frame.source_height)return;if(app.inputMode==="anchor"){let p=questionParts(app.questionKey),s=currentSubject(p.subject);s.anchor_frame_sequence=app.frame;s.anchor_source_xy=source.map((x)=>Number(x.toFixed(3)));saveDraft().then(()=>{drawPanorama();renderQuestion()});return}if(app.inputMode==="mark"){app.data.missed_person_marks.push({mark_id:crypto.randomUUID(),frame_reference_id:frame.frame_reference_id,frame_sequence:app.frame,source_xy:source.map((x)=>Number(x.toFixed(3))),role:"UNKNOWN_ROLE",certainty:"NOT_SURE"});saveDraft().then(()=>{drawPanorama();renderQuestion()});return}if(app.inputMode==="candidate"&&toggleCandidateAt(source))return;app.pointer={x:event.clientX,y:event.clientY,panX:app.view.panX,panY:app.view.panY};ui.panoramaCanvas.setPointerCapture(event.pointerId)});ui.panoramaCanvas.addEventListener("pointermove",(event)=>{if(!app.pointer)return;app.view.panX=app.pointer.panX+event.clientX-app.pointer.x;app.view.panY=app.pointer.panY+event.clientY-app.pointer.y;drawPanorama()});ui.panoramaCanvas.addEventListener("pointerup",()=>app.pointer=null);ui.panoramaCanvas.addEventListener("wheel",(event)=>{event.preventDefault();app.view.zoom=Math.max(1,Math.min(5,app.view.zoom*(event.deltaY<0?1.12:.89)));drawPanorama()},{passive:false});
ui.startRealButton.onclick=()=>loadMode("real").catch((e)=>block(`BOOT_ERROR — ${e.message}`));ui.startPracticeButton.onclick=()=>loadMode("practice").catch((e)=>block(`PRACTICE_BOOT_ERROR — ${e.message}`));ui.resetPractice.onclick=async()=>{await api("/api/practice/reset",{mode:"practice"});await loadMode("practice")};ui.helpButton.onclick=()=>{ui.helpDrawer.classList.add("open");ui.helpDrawer.setAttribute("aria-hidden","false")};ui.closeHelp.onclick=()=>{ui.helpDrawer.classList.remove("open");ui.helpDrawer.setAttribute("aria-hidden","true")};ui.nextTrancheButton.onclick=()=>{let n=Number(app.serverState.tranche_id.split("_")[1]);ui.confirmTitle.textContent=`Begin Tranche ${n+1}?`;ui.confirmDialog.showModal()};ui.confirmDialog.addEventListener("close",async()=>{if(ui.confirmDialog.returnValue!=="confirm")return;let result=await api("/api/tranche/start-next",{tranche_id:app.serverState.tranche_id});await loadMode("real",result.next_tranche_id)});ui.reviewCompletedButton.onclick=async()=>{let response=await fetch(`/api/completed?tranche=${app.serverState.tranche_id}`),payload=await response.json();if(!response.ok)throw new Error(payload.error||"completed view unavailable");app.readOnly=true;ui.saveState.textContent=`${payload.events.length} completed answers loaded read-only`;ui.reviewCompletedButton.disabled=true};
window.addEventListener("resize",resizeCanvas);document.addEventListener("keydown",(event)=>{if(event.key.toLowerCase()==="h"){ui.helpButton.click();return}if(event.code==="Space"&&app.current){event.preventDefault();togglePlayback();return}if(event.key==="ArrowLeft"&&app.current)loadFrame(app.frame-1);if(event.key==="ArrowRight"&&app.current)loadFrame(app.frame+1);let n=Number(event.key);if(n>=1&&n<=9){let button=ui.answerArea.querySelector(`[data-shortcut="${n}"]`)||ui.answerArea.querySelectorAll("[data-state]")[n-1];if(button)button.click()}});
window.__G7E_B__={app,loadMode,loadCase,loadFrame,chooseAnswer,continueQuestion,saveDraft,sourceToDisplay,displayToSource,renderQuestion,renderCompletion};
if(new URLSearchParams(location.search).get("autostart")==="1")loadMode(new URLSearchParams(location.search).get("mode")||"real").catch((e)=>block(`BOOT_ERROR — ${e.message}`));
